create table books (
    id bigint generated by default as identity primary key,
    isbn varchar(17) not null unique,
    title varchar(200) not null,
    author varchar(120) not null,
    price decimal(10,2) not null,
    version bigint not null default 0
);

insert into books (isbn, title, author, price, version)
values ('9780134685991', 'Effective Java', 'Joshua Bloch', 49.90, 0);
