server:
  port: ${PORT:8085}
spring:
  application:
    name: notification-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5537/notification}
    username: ${DB_USER:notification}
    password: ${DB_PASSWORD:training}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9192}
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      properties:
        enable.idempotence: true
    listener:
      ack-mode: record
      observation-enabled: true
    template:
      observation-enabled: true
security:
  jwt:
    secret: ${JWT_SECRET:day8-training-secret-change-me-please}
  internal-token: ${INTERNAL_SERVICE_TOKEN:day8-internal-service-token}
eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:false}
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8861/eureka/}
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState,db
  tracing:
    sampling:
      probability: 1.0
logging:
  structured:
    format:
      console: logstash
